language: python
python: 3.6
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
before_install: pip install pipenv
install: pipenv install --ignore-pipfile
script: pytest
deploy:
  provider: heroku
  api_key:
    secure: Zs61/zrZGZ4xLhSO/hU1d1cvvZi6lVUjZdSFyEJBVqy2myanwI27BrwKAKH3zuM8p57SKPR0B8QO8YGT0TLq2c5i2kT0EuD/5msM47jJjTkGn+VAPQHtxUPn/PApabbSUHyInDYzTMyVxXXpo/XQOdb+YCXegO2Y4NGAAmNgn8Gw6aSJLn4F5zvGfMMgpDcE2HawmrX/8eXu+Xjn/BN+DX7AN6jdDPpAI0bCElzgIJgVUDP3A05RPbEXSCU62MEvGlJGTcqEeKIUExUfqe/mYQud6O71e6xf9llLrAcamR+kzZLn4tQOIMHzOHvK2Zt6f6QF7LaQNT5SxXaYM2atpNc/pPW/JloxOia/n0Ua/gNqrO1Ss08QI+/vfnuBAHCdBmaQPsxTd8w4GmUU/tZPUKAq3X3GGeNFBVj+vLJYiCCEouCngoPcIyyF2K8GXnLWWjwm8QmDoaGXbm40U4PIFZPzZzYa93iD6P9XVm9ooQ/aeGU0Tm/68hDSF5bUKLPT8ACcKey/khlS1m8TkYjKjoWfA4J3mnyuKU+WoNeZz8e6nJ72PbHBxMOkL6atolnCiayZG+YuF66qBCvzJNik7iL0bFIONxX6IBLGmEnQLSaO2OIv2MO/15d/T6+sxeIl2qRbe4W1zKzIYMn2bz959piXo087ro+er4GO8yGlDBg=
notifications:
  slack:
    secure: A590PNfpWQ0QhFxCAY1xeM3ScxpxCcb9PAzhr7oytQTjIXhj777dVC6oHCKZrOQI+75ENCTsiX1o4y1mUpf9AZuR6gA33rGGPNHPJ6LqyCnCYBpmHAEDRno7rtVrOR5N0rG2zE96iazgzlRMEUBxew990iJ4IDQ5vMZgl0nCiHkc8C5fZEaa8ykUqvwMgcNhwngLZK/TOSfIkCjSqnCr8TZvOluxjOPINGkKSrYeeFc+WPzdskawtBVSBOC+T1b/uzjXc8BHmNGFWqqMGyrxT3FHIFqDi3qMz2UKYPxS1WkyGWX0SWDSyqETNaf8kqbjCMihkThqPRF9W+OPIcRoVHDoJ05xZDqfa8zxmS3fBvNdfbCN0rkW8A/MFjCIPt4w5E7/oYq5+X7vw7KVG9Ia9YEbzsXWuozjfCxrcvAAsneh86sxji0iU4k1RJqaV0G086pifydjcrkfh67lNGsZoZB2/943YeuKUgjhurkxhtRVZsFrth4LR8UOKuwJrRYx++Obmgqi4P5UMKO7BKfdPJb2hS4f1S7Aln9BhqOmZQkPjWZEmJvTnSdYDLBeOUxxX2KuCGKUJUQPEjM02q/L7gDO/ndzXF7zRKIF5WWUw4QJYD0WskiN/EbiNuJjUSdDqzROukkb+M53D4D7o/CgZUPnKveVzxoPDR332euiy7I=
