language: python
python: 3.6

branches:
  except:
    - /^v\d+\.\d+\.\d+(-\S*)?(\.\d+)?$/

stages:
  - name: test
    if: NOT (branch = master)
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      cache: pip
      before_cache:
        - rm -f $HOME/.cache/pip/log/debug.log
      before_install: pip install pipenv
      install: pipenv install
      script: pytest
    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: heroku
        app: slickbots
        api_key:
          secure: TJIbuwOOghz9SX7U1tiqtXUgRqDO4JX/WUqV6lo2KY2e0fkqlKttgDcb3b6Kj4LqZkRt5HB2qxKq8T7KWcSQNS7p0RapQMErZgl2hPieoC6XbkF74wvZOVWB2l2aCQm9fr5MdDlYIUoq7UJni45xvSf05eTOx/Hn+A2+H2K5uJFEbSRdQOsX8qkAXqbl9zJ4H+Rse993HrpsKsBjWWqObUbT58DdsDORLcR5+kwr464dDydtANOTP5i+SgxvPJZU1o+oTS/sbaUs5iOuhVwnZk+B7e/ycBnuJrTArgbcoAAcYurNpiO2+JsRCvKitLZP06tC5QmH9vrtyn7x/agCb0xM4+8dM98c56f1+aJ3uu9M/rzTm9k1SDKnJuJMM6xJ5b9oy0CGhez9BLuN0Nb/tjEwC8lHYLeKySUhykxOol3oZyQZdUoFOCbqbZmxY6DvZ8gbcS1KKvPNw5rjfTqQBy526d6Q+aShevsmQsyIQY0n3SxyG2vy+zF6la0UCg4xAL/hhyQdDy6CwPaq4ptr9Hc883yc2Qqi0DR+8HApLWfbkExa2Vqnbaqxpf1Rj7BTdMVKkqxxKYAKEPDj6RgDJ8iyNSPfwGGNruaUlom6Nbv1GI5VV5SXwZKixqPJWHH+ebWXD+XmePDTYp+WsTrNngKnHyN5z1TRALl10IuBVM0=

notifications:
  slack:
    secure: A590PNfpWQ0QhFxCAY1xeM3ScxpxCcb9PAzhr7oytQTjIXhj777dVC6oHCKZrOQI+75ENCTsiX1o4y1mUpf9AZuR6gA33rGGPNHPJ6LqyCnCYBpmHAEDRno7rtVrOR5N0rG2zE96iazgzlRMEUBxew990iJ4IDQ5vMZgl0nCiHkc8C5fZEaa8ykUqvwMgcNhwngLZK/TOSfIkCjSqnCr8TZvOluxjOPINGkKSrYeeFc+WPzdskawtBVSBOC+T1b/uzjXc8BHmNGFWqqMGyrxT3FHIFqDi3qMz2UKYPxS1WkyGWX0SWDSyqETNaf8kqbjCMihkThqPRF9W+OPIcRoVHDoJ05xZDqfa8zxmS3fBvNdfbCN0rkW8A/MFjCIPt4w5E7/oYq5+X7vw7KVG9Ia9YEbzsXWuozjfCxrcvAAsneh86sxji0iU4k1RJqaV0G086pifydjcrkfh67lNGsZoZB2/943YeuKUgjhurkxhtRVZsFrth4LR8UOKuwJrRYx++Obmgqi4P5UMKO7BKfdPJb2hS4f1S7Aln9BhqOmZQkPjWZEmJvTnSdYDLBeOUxxX2KuCGKUJUQPEjM02q/L7gDO/ndzXF7zRKIF5WWUw4QJYD0WskiN/EbiNuJjUSdDqzROukkb+M53D4D7o/CgZUPnKveVzxoPDR332euiy7I=
