language: python
python: 3.6
before_install: pip install pipenv
install: pipenv install --ignore-pipfile
script: pytest
notifications:
  slack:
    secure: A590PNfpWQ0QhFxCAY1xeM3ScxpxCcb9PAzhr7oytQTjIXhj777dVC6oHCKZrOQI+75ENCTsiX1o4y1mUpf9AZuR6gA33rGGPNHPJ6LqyCnCYBpmHAEDRno7rtVrOR5N0rG2zE96iazgzlRMEUBxew990iJ4IDQ5vMZgl0nCiHkc8C5fZEaa8ykUqvwMgcNhwngLZK/TOSfIkCjSqnCr8TZvOluxjOPINGkKSrYeeFc+WPzdskawtBVSBOC+T1b/uzjXc8BHmNGFWqqMGyrxT3FHIFqDi3qMz2UKYPxS1WkyGWX0SWDSyqETNaf8kqbjCMihkThqPRF9W+OPIcRoVHDoJ05xZDqfa8zxmS3fBvNdfbCN0rkW8A/MFjCIPt4w5E7/oYq5+X7vw7KVG9Ia9YEbzsXWuozjfCxrcvAAsneh86sxji0iU4k1RJqaV0G086pifydjcrkfh67lNGsZoZB2/943YeuKUgjhurkxhtRVZsFrth4LR8UOKuwJrRYx++Obmgqi4P5UMKO7BKfdPJb2hS4f1S7Aln9BhqOmZQkPjWZEmJvTnSdYDLBeOUxxX2KuCGKUJUQPEjM02q/L7gDO/ndzXF7zRKIF5WWUw4QJYD0WskiN/EbiNuJjUSdDqzROukkb+M53D4D7o/CgZUPnKveVzxoPDR332euiy7I=
